### ISSUE TITLE
Implement DNS based architecture

### ISSUE THREAD

**Issue by Stormtv** [Stormtv/nano-alias#7]
Instead of a single system that handles aliases such as @stormtv etc. We will be moving to a more decentralized DNS based system. Aliases will instead be more like emails and look like @stormtv.getcanoe.io

Benefits:
1. No central authority on who is hosting the aliases. The network will be distributed on people's personal DNS servers. If one server crashes the network is still intact.
2. No squatting, I can't just take @starbucks anymore. I would have to own the starbucks.com domain and register @joe.starbucks.com
3. No fighting over short aliases now there are unlimited aliases

Cons:

1. Longer Aliases
2. Somewhat confusing similarity to email addresses
3. Running an alias server on your domain might require some computer knowledge but services like canoe and other community members will offer alias hosting.
4. Not sure how to implement phone number aliases on a distributed alias system. Might rely on core to host all the phone number aliases.

**Comment by NiFNi** [comment]
I like this concept. 
To your cons:

1. Longer aliases won't be such a problem as *.nano.org, *.getcanoe.io, *.nanovault.io and maybe one or two more people/groups that will be used for 90% of the aliases. So that's pretty easy to get. 

2. The alias can look different. For example stormtv:getcanoe.io which removes the @ (which is probably a big part of thinking about an email when seing an alias) and enables subdomains while keeping it pretty clear where the alias ends and the domain starts. We could even turn the whole thing around and make it getcanoe.io:stormtv. 

3. This is definitely one of the biggest problems. Apart from that hosting a server can't be done by everyone it's also something that maybe should not be done by everyone. Capturing alias servers could be highly profitable. This can be a big security problem.

4. Phone numbers is a problem. Adding phone numbers always needs some kind of SMS verification (AFAIK) which can't really be done decentralized (again AFAIK). So maybe for now should just leave this out. While it would be cool to match addresses to phone numbers I don't think it is needed when everyone has a nickname in the internet which can be used with a preferred server. 

Two points from my side:
1. I think in wallets a feature should be implemented that notifies users if the address associated with an aliases changed since the last time a send was issued to that alias. This can negotiate atleast some of the trust issues with this system. Server owners can't change aliases that easily without anyone noticing.
2. SRV records should be supported so that people running servers can be more flexible.

**Comment by Stormtv** [comment]
@NiFNi 

2. Maybe aliases could be $stormtv.getcanoe.io have the cash symbol be our identifier to differentiate from email.

3. We will have to offer an easy integration guide but even in the case of a server being hacked the icon representing an alias will change and hopefully alert the user.

In response to your points:

1. That was the purpose of the [signatures & generated images](https://github.com/Stormtv/nano-alias#signatures--editing). The wallet can detect if there was a change of an alias from the previous address to a new address and easily warn the users. We should definitely recommend client implementations to have this functionality  

2. I'm not familiar with SRV records but definitely willing to learn about them and how it could help

**Comment by NiFNi** [comment]
Cash symbol sounds great. 
Ah yeah the icons are a nice way to solve this. 

And SRV records make it possible to redirect specific services to a port and IP specified in DNS records. For example that way it would be easy to run the alias service from another host than the canoe website without the need of additional software or subdomains. Also as you can specify the port it does not matter which port you want to listen the service on.

**Comment by cryptocode** [comment]
The `@` symbol is more or less universal in tagging/searching people, Twitter and Facebook included. I think that should be used here as well - I don't think confusing it with an email should be a problem, esp if UI's does even basic validation (and hints to begin with)

**Comment by Stormtv** [comment]
I'm pretty much closing development on this project as I worked with https://github.com/opencap to help design their solution. I might rebuild this project as a OpenCap Broker.
